// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/repository (interfaces: EmailTokenRepository)

package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/repository/entity"
	enums "github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/repository/entity/enums"
	gomock "go.uber.org/mock/gomock"
)

type MockEmailTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEmailTokenRepositoryMockRecorder
}

type MockEmailTokenRepositoryMockRecorder struct {
	mock *MockEmailTokenRepository
}

func NewMockEmailTokenRepository(ctrl *gomock.Controller) *MockEmailTokenRepository {
	mock := &MockEmailTokenRepository{ctrl: ctrl}
	mock.recorder = &MockEmailTokenRepositoryMockRecorder{mock}
	return mock
}

func (m *MockEmailTokenRepository) EXPECT() *MockEmailTokenRepositoryMockRecorder {
	return m.recorder
}

func (m *MockEmailTokenRepository) Save(ctx context.Context, userID, tokenHash string, tokenType enums.EmailTokenType, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userID, tokenHash, tokenType, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEmailTokenRepositoryMockRecorder) Save(ctx, userID, tokenHash, tokenType, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEmailTokenRepository)(nil).Save), ctx, userID, tokenHash, tokenType, expiresAt)
}

func (m *MockEmailTokenRepository) FindByHashAndType(ctx context.Context, tokenHash string, tokenType enums.EmailTokenType) (*entity.EmailTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHashAndType", ctx, tokenHash, tokenType)
	ret0, _ := ret[0].(*entity.EmailTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockEmailTokenRepositoryMockRecorder) FindByHashAndType(ctx, tokenHash, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHashAndType", reflect.TypeOf((*MockEmailTokenRepository)(nil).FindByHashAndType), ctx, tokenHash, tokenType)
}

func (m *MockEmailTokenRepository) DeleteByHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEmailTokenRepositoryMockRecorder) DeleteByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByHash", reflect.TypeOf((*MockEmailTokenRepository)(nil).DeleteByHash), ctx, tokenHash)
}

func (m *MockEmailTokenRepository) DeleteByUserIDAndType(ctx context.Context, userID string, tokenType enums.EmailTokenType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserIDAndType", ctx, userID, tokenType)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEmailTokenRepositoryMockRecorder) DeleteByUserIDAndType(ctx, userID, tokenType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserIDAndType", reflect.TypeOf((*MockEmailTokenRepository)(nil).DeleteByUserIDAndType), ctx, userID, tokenType)
}
