// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/repository (interfaces: CostRepository)

package mocks

import (
	context "context"
	reflect "reflect"

	domains "github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockCostRepository is a mock of CostRepository interface.
type MockCostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCostRepositoryMockRecorder
}

// MockCostRepositoryMockRecorder is the mock recorder for MockCostRepository.
type MockCostRepositoryMockRecorder struct {
	mock *MockCostRepository
}

// NewMockCostRepository creates a new mock instance.
func NewMockCostRepository(ctrl *gomock.Controller) *MockCostRepository {
	mock := &MockCostRepository{ctrl: ctrl}
	mock.recorder = &MockCostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCostRepository) EXPECT() *MockCostRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCostRepository) Create(ctx context.Context, cost *domains.Cost) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cost)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCostRepositoryMockRecorder) Create(ctx, cost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCostRepository)(nil).Create), ctx, cost)
}

// Update mocks base method.
func (m *MockCostRepository) Update(ctx context.Context, id string, cost *domains.Cost) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, cost)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCostRepositoryMockRecorder) Update(ctx, id, cost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCostRepository)(nil).Update), ctx, id, cost)
}

// FindAll mocks base method.
func (m *MockCostRepository) FindAll(ctx context.Context, userID string, limit, offset int, filters domains.CostFilters) ([]*domains.Cost, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, userID, limit, offset, filters)
	ret0, _ := ret[0].([]*domains.Cost)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCostRepositoryMockRecorder) FindAll(ctx, userID, limit, offset, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCostRepository)(nil).FindAll), ctx, userID, limit, offset, filters)
}

// FindByID mocks base method.
func (m *MockCostRepository) FindByID(ctx context.Context, id string) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCostRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCostRepository)(nil).FindByID), ctx, id)
}

// Delete mocks base method.
func (m *MockCostRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCostRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCostRepository)(nil).Delete), ctx, id)
}

// FindStats mocks base method.
func (m *MockCostRepository) FindStats(ctx context.Context, userID string, filters domains.CostFilters) (*domains.CostStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStats", ctx, userID, filters)
	ret0, _ := ret[0].(*domains.CostStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStats indicates an expected call of FindStats.
func (mr *MockCostRepositoryMockRecorder) FindStats(ctx, userID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStats", reflect.TypeOf((*MockCostRepository)(nil).FindStats), ctx, userID, filters)
}
