// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/repository (interfaces: ContactRepository)

package mocks

import (
	context "context"
	reflect "reflect"

	domains "github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/domains"
	gomock "go.uber.org/mock/gomock"
)

type MockContactRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContactRepositoryMockRecorder
}

type MockContactRepositoryMockRecorder struct {
	mock *MockContactRepository
}

func NewMockContactRepository(ctrl *gomock.Controller) *MockContactRepository {
	mock := &MockContactRepository{ctrl: ctrl}
	mock.recorder = &MockContactRepositoryMockRecorder{mock}
	return mock
}

func (m *MockContactRepository) EXPECT() *MockContactRepositoryMockRecorder {
	return m.recorder
}

func (m *MockContactRepository) Create(ctx context.Context, contact *domains.Contact) (*domains.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, contact)
	ret0, _ := ret[0].(*domains.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockContactRepositoryMockRecorder) Create(ctx, contact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContactRepository)(nil).Create), ctx, contact)
}

func (m *MockContactRepository) FindAll(ctx context.Context, ownerID string, limit, offset int, filters domains.ContactFilters) ([]*domains.Contact, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, ownerID, limit, offset, filters)
	ret0, _ := ret[0].([]*domains.Contact)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockContactRepositoryMockRecorder) FindAll(ctx, ownerID, limit, offset, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockContactRepository)(nil).FindAll), ctx, ownerID, limit, offset, filters)
}

func (m *MockContactRepository) FindByID(ctx context.Context, id string) (*domains.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domains.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockContactRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockContactRepository)(nil).FindByID), ctx, id)
}

func (m *MockContactRepository) Update(ctx context.Context, contact *domains.Contact) (*domains.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, contact)
	ret0, _ := ret[0].(*domains.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockContactRepositoryMockRecorder) Update(ctx, contact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContactRepository)(nil).Update), ctx, contact)
}

func (m *MockContactRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockContactRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContactRepository)(nil).Delete), ctx, id)
}

func (m *MockContactRepository) ExistsByEmailAndOwner(ctx context.Context, email, ownerID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmailAndOwner", ctx, email, ownerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockContactRepositoryMockRecorder) ExistsByEmailAndOwner(ctx, email, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmailAndOwner", reflect.TypeOf((*MockContactRepository)(nil).ExistsByEmailAndOwner), ctx, email, ownerID)
}

func (m *MockContactRepository) FindStats(ctx context.Context, ownerID string) (*domains.ContactStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStats", ctx, ownerID)
	ret0, _ := ret[0].(*domains.ContactStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockContactRepositoryMockRecorder) FindStats(ctx, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStats", reflect.TypeOf((*MockContactRepository)(nil).FindStats), ctx, ownerID)
}

func (m *MockContactRepository) FindContactsByFrequency(ctx context.Context, userID string, limit int) ([]domains.ContactFrequency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindContactsByFrequency", ctx, userID, limit)
	ret0, _ := ret[0].([]domains.ContactFrequency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockContactRepositoryMockRecorder) FindContactsByFrequency(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindContactsByFrequency", reflect.TypeOf((*MockContactRepository)(nil).FindContactsByFrequency), ctx, userID, limit)
}
