// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/repository (interfaces: AuthRepository)

package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/repository/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockAuthRepository) Save(ctx context.Context, userID string, tokenHash string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userID, tokenHash, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAuthRepositoryMockRecorder) Save(ctx, userID, tokenHash, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAuthRepository)(nil).Save), ctx, userID, tokenHash, expiresAt)
}

// FindByHash mocks base method.
func (m *MockAuthRepository) FindByHash(ctx context.Context, tokenHash string) (*entity.RefreshTokenEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, tokenHash)
	ret0, _ := ret[0].(*entity.RefreshTokenEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockAuthRepositoryMockRecorder) FindByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockAuthRepository)(nil).FindByHash), ctx, tokenHash)
}

// DeleteByHash mocks base method.
func (m *MockAuthRepository) DeleteByHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByHash indicates an expected call of DeleteByHash.
func (mr *MockAuthRepositoryMockRecorder) DeleteByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByHash", reflect.TypeOf((*MockAuthRepository)(nil).DeleteByHash), ctx, tokenHash)
}

// DeleteByUserID mocks base method.
func (m *MockAuthRepository) DeleteByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockAuthRepositoryMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockAuthRepository)(nil).DeleteByUserID), ctx, userID)
}
