// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/service (interfaces: EmailService)

package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
}

type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

func (m *MockEmailService) SendVerificationEmail(ctx context.Context, toEmail, userName, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationEmail", ctx, toEmail, userName, token)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEmailServiceMockRecorder) SendVerificationEmail(ctx, toEmail, userName, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationEmail", reflect.TypeOf((*MockEmailService)(nil).SendVerificationEmail), ctx, toEmail, userName, token)
}

func (m *MockEmailService) SendPasswordResetEmail(ctx context.Context, toEmail, userName, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordResetEmail", ctx, toEmail, userName, token)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockEmailServiceMockRecorder) SendPasswordResetEmail(ctx, toEmail, userName, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordResetEmail", reflect.TypeOf((*MockEmailService)(nil).SendPasswordResetEmail), ctx, toEmail, userName, token)
}
