// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/repository (interfaces: ContactRepository)

package mocks

import (
	reflect "reflect"

	domains "github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/domains"
	gomock "go.uber.org/mock/gomock"
)

type MockContactRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContactRepositoryMockRecorder
}

type MockContactRepositoryMockRecorder struct {
	mock *MockContactRepository
}

func NewMockContactRepository(ctrl *gomock.Controller) *MockContactRepository {
	mock := &MockContactRepository{ctrl: ctrl}
	mock.recorder = &MockContactRepositoryMockRecorder{mock}
	return mock
}

func (m *MockContactRepository) EXPECT() *MockContactRepositoryMockRecorder {
	return m.recorder
}

func (m *MockContactRepository) Create(contact *domains.Contact) (*domains.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", contact)
	ret0, _ := ret[0].(*domains.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockContactRepositoryMockRecorder) Create(contact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContactRepository)(nil).Create), contact)
}

func (m *MockContactRepository) FindAll(ownerID string) ([]*domains.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ownerID)
	ret0, _ := ret[0].([]*domains.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockContactRepositoryMockRecorder) FindAll(ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockContactRepository)(nil).FindAll), ownerID)
}

func (m *MockContactRepository) FindByID(id string) (*domains.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*domains.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockContactRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockContactRepository)(nil).FindByID), id)
}

func (m *MockContactRepository) Update(contact *domains.Contact) (*domains.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", contact)
	ret0, _ := ret[0].(*domains.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockContactRepositoryMockRecorder) Update(contact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContactRepository)(nil).Update), contact)
}

func (m *MockContactRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockContactRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContactRepository)(nil).Delete), id)
}

func (m *MockContactRepository) ExistsByEmailAndOwner(email, ownerID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmailAndOwner", email, ownerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockContactRepositoryMockRecorder) ExistsByEmailAndOwner(email, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmailAndOwner", reflect.TypeOf((*MockContactRepository)(nil).ExistsByEmailAndOwner), email, ownerID)
}
