// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/service (interfaces: CostService)

package mocks

import (
	context "context"
	reflect "reflect"

	domains "github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockCostService is a mock of CostService interface.
type MockCostService struct {
	ctrl     *gomock.Controller
	recorder *MockCostServiceMockRecorder
}

// MockCostServiceMockRecorder is the mock recorder for MockCostService.
type MockCostServiceMockRecorder struct {
	mock *MockCostService
}

// NewMockCostService creates a new mock instance.
func NewMockCostService(ctrl *gomock.Controller) *MockCostService {
	mock := &MockCostService{ctrl: ctrl}
	mock.recorder = &MockCostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCostService) EXPECT() *MockCostServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCostService) Create(ctx context.Context, cost *domains.Cost, ownerPercentage *float64) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cost, ownerPercentage)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCostServiceMockRecorder) Create(ctx, cost, ownerPercentage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCostService)(nil).Create), ctx, cost, ownerPercentage)
}

// Update mocks base method.
func (m *MockCostService) Update(ctx context.Context, id, userID string, cost *domains.Cost, ownerPercentage *float64) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, userID, cost, ownerPercentage)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCostServiceMockRecorder) Update(ctx, id, userID, cost, ownerPercentage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCostService)(nil).Update), ctx, id, userID, cost, ownerPercentage)
}

// FindAll mocks base method.
func (m *MockCostService) FindAll(ctx context.Context, userID string, page, limit int, filters domains.CostFilters) ([]*domains.Cost, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, userID, page, limit, filters)
	ret0, _ := ret[0].([]*domains.Cost)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCostServiceMockRecorder) FindAll(ctx, userID, page, limit, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCostService)(nil).FindAll), ctx, userID, page, limit, filters)
}

// FindByID mocks base method.
func (m *MockCostService) FindByID(ctx context.Context, id, userID string) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id, userID)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCostServiceMockRecorder) FindByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCostService)(nil).FindByID), ctx, id, userID)
}

// FindStats mocks base method.
func (m *MockCostService) FindStats(ctx context.Context, userID string, filters domains.CostFilters) (*domains.CostStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStats", ctx, userID, filters)
	ret0, _ := ret[0].(*domains.CostStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStats indicates an expected call of FindStats.
func (mr *MockCostServiceMockRecorder) FindStats(ctx, userID, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStats", reflect.TypeOf((*MockCostService)(nil).FindStats), ctx, userID, filters)
}

// Delete mocks base method.
func (m *MockCostService) Delete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCostServiceMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCostService)(nil).Delete), ctx, id, userID)
}
