// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/repository/group_repository_impl.go
//
// Generated by this command:
//
//	mockgen -source=internal/model/repository/group_repository_impl.go -destination=internal/mocks/mock_group_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domains "github.com/rafabcanedo/gonna-pay/gonna-pay-backend/internal/model/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupRepository is a mock of GroupRepository interface.
type MockGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockGroupRepositoryMockRecorder is the mock recorder for MockGroupRepository.
type MockGroupRepositoryMockRecorder struct {
	mock *MockGroupRepository
}

// NewMockGroupRepository creates a new mock instance.
func NewMockGroupRepository(ctrl *gomock.Controller) *MockGroupRepository {
	mock := &MockGroupRepository{ctrl: ctrl}
	mock.recorder = &MockGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupRepository) EXPECT() *MockGroupRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockGroupRepository) AddMember(groupID, contactID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", groupID, contactID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockGroupRepositoryMockRecorder) AddMember(groupID, contactID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockGroupRepository)(nil).AddMember), groupID, contactID)
}

// Create mocks base method.
func (m *MockGroupRepository) Create(group *domains.Group, memberIDs []string) (*domains.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", group, memberIDs)
	ret0, _ := ret[0].(*domains.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGroupRepositoryMockRecorder) Create(group, memberIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupRepository)(nil).Create), group, memberIDs)
}

// Delete mocks base method.
func (m *MockGroupRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupRepository)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockGroupRepository) FindAll(ownerID string) ([]*domains.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ownerID)
	ret0, _ := ret[0].([]*domains.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockGroupRepositoryMockRecorder) FindAll(ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockGroupRepository)(nil).FindAll), ownerID)
}

// FindByID mocks base method.
func (m *MockGroupRepository) FindByID(id string) (*domains.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*domains.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockGroupRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockGroupRepository)(nil).FindByID), id)
}

// IsContactOwnedBy mocks base method.
func (m *MockGroupRepository) IsContactOwnedBy(contactID, ownerID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsContactOwnedBy", contactID, ownerID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsContactOwnedBy indicates an expected call of IsContactOwnedBy.
func (mr *MockGroupRepositoryMockRecorder) IsContactOwnedBy(contactID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsContactOwnedBy", reflect.TypeOf((*MockGroupRepository)(nil).IsContactOwnedBy), contactID, ownerID)
}

// MemberExists mocks base method.
func (m *MockGroupRepository) MemberExists(groupID, contactID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemberExists", groupID, contactID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemberExists indicates an expected call of MemberExists.
func (mr *MockGroupRepositoryMockRecorder) MemberExists(groupID, contactID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemberExists", reflect.TypeOf((*MockGroupRepository)(nil).MemberExists), groupID, contactID)
}

// RemoveMember mocks base method.
func (m *MockGroupRepository) RemoveMember(groupID, contactID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", groupID, contactID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockGroupRepositoryMockRecorder) RemoveMember(groupID, contactID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockGroupRepository)(nil).RemoveMember), groupID, contactID)
}

// Update mocks base method.
func (m *MockGroupRepository) Update(group *domains.Group) (*domains.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", group)
	ret0, _ := ret[0].(*domains.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGroupRepositoryMockRecorder) Update(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupRepository)(nil).Update), group)
}
