// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafabcanedo/basic-internal-system/internal-system-backend/internal/model/service (interfaces: GroupService)

package mocks

import (
	reflect "reflect"

	domains "github.com/rafabcanedo/basic-internal-system/internal-system-backend/internal/model/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupService is a mock of GroupService interface.
type MockGroupService struct {
	ctrl     *gomock.Controller
	recorder *MockGroupServiceMockRecorder
}

// MockGroupServiceMockRecorder is the mock recorder for MockGroupService.
type MockGroupServiceMockRecorder struct {
	mock *MockGroupService
}

// NewMockGroupService creates a new mock instance.
func NewMockGroupService(ctrl *gomock.Controller) *MockGroupService {
	mock := &MockGroupService{ctrl: ctrl}
	mock.recorder = &MockGroupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupService) EXPECT() *MockGroupServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGroupService) Create(group *domains.Group, memberIDs []string) (*domains.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", group, memberIDs)
	ret0, _ := ret[0].(*domains.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGroupServiceMockRecorder) Create(group, memberIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupService)(nil).Create), group, memberIDs)
}

// FindAll mocks base method.
func (m *MockGroupService) FindAll(ownerID string) ([]*domains.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ownerID)
	ret0, _ := ret[0].([]*domains.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockGroupServiceMockRecorder) FindAll(ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockGroupService)(nil).FindAll), ownerID)
}

// FindByID mocks base method.
func (m *MockGroupService) FindByID(id, ownerID string) (*domains.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id, ownerID)
	ret0, _ := ret[0].(*domains.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockGroupServiceMockRecorder) FindByID(id, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockGroupService)(nil).FindByID), id, ownerID)
}

// Delete mocks base method.
func (m *MockGroupService) Delete(id, ownerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupServiceMockRecorder) Delete(id, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupService)(nil).Delete), id, ownerID)
}

// AddMember mocks base method.
func (m *MockGroupService) AddMember(groupID, contactID, ownerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", groupID, contactID, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockGroupServiceMockRecorder) AddMember(groupID, contactID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockGroupService)(nil).AddMember), groupID, contactID, ownerID)
}

// RemoveMember mocks base method.
func (m *MockGroupService) RemoveMember(groupID, contactID, ownerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", groupID, contactID, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockGroupServiceMockRecorder) RemoveMember(groupID, contactID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockGroupService)(nil).RemoveMember), groupID, contactID, ownerID)
}
