// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafabcanedo/basic-internal-system/internal-system-backend/internal/model/repository (interfaces: CostRepository)

package mocks

import (
	reflect "reflect"

	domains "github.com/rafabcanedo/basic-internal-system/internal-system-backend/internal/model/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockCostRepository is a mock of CostRepository interface.
type MockCostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCostRepositoryMockRecorder
}

// MockCostRepositoryMockRecorder is the mock recorder for MockCostRepository.
type MockCostRepositoryMockRecorder struct {
	mock *MockCostRepository
}

// NewMockCostRepository creates a new mock instance.
func NewMockCostRepository(ctrl *gomock.Controller) *MockCostRepository {
	mock := &MockCostRepository{ctrl: ctrl}
	mock.recorder = &MockCostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCostRepository) EXPECT() *MockCostRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCostRepository) Create(cost *domains.Cost, memberIDs []string) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", cost, memberIDs)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCostRepositoryMockRecorder) Create(cost, memberIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCostRepository)(nil).Create), cost, memberIDs)
}

// Update mocks base method.
func (m *MockCostRepository) Update(id string, cost *domains.Cost) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, cost)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCostRepositoryMockRecorder) Update(id, cost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCostRepository)(nil).Update), id, cost)
}

// FindAll mocks base method.
func (m *MockCostRepository) FindAll(userID string) ([]*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", userID)
	ret0, _ := ret[0].([]*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCostRepositoryMockRecorder) FindAll(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCostRepository)(nil).FindAll), userID)
}

// FindByID mocks base method.
func (m *MockCostRepository) FindByID(id string) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCostRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCostRepository)(nil).FindByID), id)
}

// Delete mocks base method.
func (m *MockCostRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCostRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCostRepository)(nil).Delete), id)
}

// GetGroupMemberIDs mocks base method.
func (m *MockCostRepository) GetGroupMemberIDs(groupID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupMemberIDs", groupID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupMemberIDs indicates an expected call of GetGroupMemberIDs.
func (mr *MockCostRepositoryMockRecorder) GetGroupMemberIDs(groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupMemberIDs", reflect.TypeOf((*MockCostRepository)(nil).GetGroupMemberIDs), groupID)
}

// GetGroupName mocks base method.
func (m *MockCostRepository) GetGroupName(groupID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupName", groupID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupName indicates an expected call of GetGroupName.
func (mr *MockCostRepositoryMockRecorder) GetGroupName(groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupName", reflect.TypeOf((*MockCostRepository)(nil).GetGroupName), groupID)
}
