// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafabcanedo/basic-internal-system/internal-system-backend/internal/model/service (interfaces: ContactService)

package mocks

import (
	reflect "reflect"

	domains "github.com/rafabcanedo/basic-internal-system/internal-system-backend/internal/model/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockContactService is a mock of ContactService interface.
type MockContactService struct {
	ctrl     *gomock.Controller
	recorder *MockContactServiceMockRecorder
}

// MockContactServiceMockRecorder is the mock recorder for MockContactService.
type MockContactServiceMockRecorder struct {
	mock *MockContactService
}

// NewMockContactService creates a new mock instance.
func NewMockContactService(ctrl *gomock.Controller) *MockContactService {
	mock := &MockContactService{ctrl: ctrl}
	mock.recorder = &MockContactServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactService) EXPECT() *MockContactServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockContactService) Create(domain domains.ContactDomainInterface) (domains.ContactDomainInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", domain)
	ret0, _ := ret[0].(domains.ContactDomainInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockContactServiceMockRecorder) Create(domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContactService)(nil).Create), domain)
}

// FindAll mocks base method.
func (m *MockContactService) FindAll(ownerID string) ([]domains.ContactDomainInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ownerID)
	ret0, _ := ret[0].([]domains.ContactDomainInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockContactServiceMockRecorder) FindAll(ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockContactService)(nil).FindAll), ownerID)
}

// FindByID mocks base method.
func (m *MockContactService) FindByID(id, ownerID string) (domains.ContactDomainInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id, ownerID)
	ret0, _ := ret[0].(domains.ContactDomainInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockContactServiceMockRecorder) FindByID(id, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockContactService)(nil).FindByID), id, ownerID)
}

// Update mocks base method.
func (m *MockContactService) Update(domain domains.ContactDomainInterface) (domains.ContactDomainInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", domain)
	ret0, _ := ret[0].(domains.ContactDomainInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockContactServiceMockRecorder) Update(domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContactService)(nil).Update), domain)
}

// Delete mocks base method.
func (m *MockContactService) Delete(id, ownerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContactServiceMockRecorder) Delete(id, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContactService)(nil).Delete), id, ownerID)
}
