// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafabcanedo/basic-internal-system/internal-system-backend/internal/model/service (interfaces: CostService)

package mocks

import (
	reflect "reflect"

	domains "github.com/rafabcanedo/basic-internal-system/internal-system-backend/internal/model/domains"
	gomock "go.uber.org/mock/gomock"
)

// MockCostService is a mock of CostService interface.
type MockCostService struct {
	ctrl     *gomock.Controller
	recorder *MockCostServiceMockRecorder
}

// MockCostServiceMockRecorder is the mock recorder for MockCostService.
type MockCostServiceMockRecorder struct {
	mock *MockCostService
}

// NewMockCostService creates a new mock instance.
func NewMockCostService(ctrl *gomock.Controller) *MockCostService {
	mock := &MockCostService{ctrl: ctrl}
	mock.recorder = &MockCostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCostService) EXPECT() *MockCostServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCostService) Create(cost *domains.Cost, ownerPercentage *float64) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", cost, ownerPercentage)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCostServiceMockRecorder) Create(cost, ownerPercentage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCostService)(nil).Create), cost, ownerPercentage)
}

// Update mocks base method.
func (m *MockCostService) Update(id, userID string, cost *domains.Cost, ownerPercentage *float64) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, userID, cost, ownerPercentage)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCostServiceMockRecorder) Update(id, userID, cost, ownerPercentage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCostService)(nil).Update), id, userID, cost, ownerPercentage)
}

// FindAll mocks base method.
func (m *MockCostService) FindAll(userID string) ([]*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", userID)
	ret0, _ := ret[0].([]*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCostServiceMockRecorder) FindAll(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCostService)(nil).FindAll), userID)
}

// FindByID mocks base method.
func (m *MockCostService) FindByID(id, userID string) (*domains.Cost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id, userID)
	ret0, _ := ret[0].(*domains.Cost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCostServiceMockRecorder) FindByID(id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCostService)(nil).FindByID), id, userID)
}

// Delete mocks base method.
func (m *MockCostService) Delete(id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCostServiceMockRecorder) Delete(id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCostService)(nil).Delete), id, userID)
}
