import type { Metadata } from "next";
import { Poppins, Roboto, Open_Sans, Montserrat } from "next/font/google";
import "../globals.css";
import { ReactNode } from "react";
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SideBar } from "@/components/side-bar";
import { AppProviders } from "@/providers";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const openSans = Open_Sans({
  variable: "--font-opens",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Internal System",
  description: "Generated by create next app",
};

export default function PrivateLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
                ${poppins.variable}
                ${roboto.variable}
                ${openSans.variable}
                ${montserrat.variable}
                antialiased
              `}
      >
        <AppProviders>
          <SidebarProvider>
            <SideBar />
            <main className="flex-1 px-8">{children}</main>
          </SidebarProvider>
          <Toaster richColors position="bottom-center" />
        </AppProviders>
      </body>
    </html>
  );
}
